name: Push to main

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - run: npm ci

      - name: Linting
        run: npm run lint

      - name: Unit testiing
        run: npm test

      - name: E2E testing
        run: npm run test:e2e

      - name: Build
        run: npm run build

      - name: Deploy
        run: echo "Deploying!"
